### ISSUE TITLE
对齐专家原则的第二步中 ，self-instruct的众多query的answer怎么产生的

### ISSUE THREAD

**Issue by cocoandoral** [X-PLUG/CValues#2]
第二步中 ，self-instruct的众多的query，其对应的answer又是怎么产生的呢

**Comment by xuguohai** [comment]
输入query+相应的专家原则到大模型中，让大模型输出answer. （相当于大模型输出答案时，会参考专家原则来输出合适的答案）

**Comment by cocoandoral** [comment]
感谢回复。  还有一点疑问：模型本身的知识是既定的，加上专家原则就能生成 符合预期的answer吗？ 是不是需要要学习专家标注的900个问题。 然后再用专家原则指导输出answer

**Comment by xuguohai** [comment]
我们的方法主要解决模型的意识问题，很多时候模型本身的知识已经能够回答这个问题了，只是因为没有对齐人类的价值取向，所以输出了被人类认为不符合价值观的回复。 加上专家原则，就是引导模型往正确角度来回复问题，所以模型的知识虽然是既定的，但也能生成符合预期的answer。 因此，在我们的实验中，没有事先学习专家的问题和答案。不过，提前学习肯定是可以的。

当然，这种做法非常轻量，主要解决意识错误问题，但由于其他原因造成不安全或不负责的回复，比如“逻辑混乱矛盾”、“专业知识理解与应用不足”等问题，肯定是要加强模型基础能力、学习更多知识，才能解决好。
