### ISSUE TITLE
dataset train.jsonl有问题

### ISSUE THREAD

**Issue by zhanghaoie** [X-PLUG/CValues#4]

**Comment by zhanghaoie** [comment]
下载下来是空文件？

**Comment by xuguohai** [comment]
modelscope上的train.jsonl先git lfs install一下，然后再git clone 

可以参考：https://www.modelscope.cn/docs/%E6%95%B0%E6%8D%AE%E9%9B%86%E7%9A%84%E4%B8%8B%E8%BD%BD
